### ISSUE TITLE
Performance VS to_a.paginate

### ISSUE THREAD

**Issue by chrislgrigg** [dnagir/neo4j-will_paginate#6]
I've found that calling paginate on a Neo4j.rb 2.3.0 query result takes on average twice as long as calling to_a.paginate on that same result. For instance, a traversal:

![image](https://f.cloud.github.com/assets/4097271/2224738/9018c468-9a82-11e3-96d1-b3761a7af054.png)

A lucene query: 

![image](https://f.cloud.github.com/assets/4097271/2224828/6b75a896-9a83-11e3-90fe-dbef148c83d8.png)

It's also twice as fast to run a Cypher query against a user that specifies the relationship, convert the results to array, and paginate that than run the same query straight from the user.

![image](https://f.cloud.github.com/assets/4097271/2224817/34c0553a-9a83-11e3-9048-c5136f1919d0.png)

Is there a benefit to using paginate directly on results that I am missing? Is there a problem somewhere that needs to be corrected?

**Comment by andreasronge** [comment]
Looks like there is a problem somewhere in neo4j.rb.
Sorry, but I don't have time to fix it. I will of course accept a pull request.
On my spare time I'm working on the new 3.0 version.
